"""create representatives table && followers thru table

Revision ID: 295672145ed7
Revises: c46c1aea3962
Create Date: 2021-01-05 18:29:33.157509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295672145ed7'
down_revision = 'c46c1aea3962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bioguide_id', sa.String(length=20), nullable=False),
    sa.Column('short_title', sa.String(length=5), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('party', sa.String(length=2), nullable=False),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('facebook_handle', sa.String(length=100), nullable=True),
    sa.Column('youtube_handle', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('contact_url', sa.String(length=500), nullable=True),
    sa.Column('in_office', sa.Boolean(), nullable=False),
    sa.Column('next_election', sa.DateTime(), nullable=True),
    sa.Column('ocd_id', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('state_id', sa.String(length=2), nullable=False),
    sa.Column('missed_votes_pct', sa.Float(), nullable=True),
    sa.Column('votes_with_party_pct', sa.Float(), nullable=True),
    sa.Column('votes_against_party_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.abbreviation'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_constituent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('representative_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    op.drop_table('representatives')
    # ### end Alembic commands ###
