"""create rep_votes table

Revision ID: ebeb94c4b081
Revises: 97288ff6c9a9
Create Date: 2021-01-15 15:26:42.298862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebeb94c4b081'
down_revision = '97288ff6c9a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rep_votes',
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_downvote', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('representative_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rep_votes')
    # ### end Alembic commands ###
