"""create all tables

Revision ID: 97288ff6c9a9
Revises: 
Create Date: 2021-01-11 19:26:47.026350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97288ff6c9a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('abbreviation', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbreviation'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('zip_code', sa.String(length=5), nullable=False),
    sa.Column('is_registered_voter', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('representatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bioguide_id', sa.String(length=20), nullable=False),
    sa.Column('short_title', sa.String(length=5), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=False),
    sa.Column('last_name', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('party', sa.String(length=2), nullable=False),
    sa.Column('twitter_handle', sa.String(length=100), nullable=True),
    sa.Column('facebook_handle', sa.String(length=100), nullable=True),
    sa.Column('youtube_handle', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('contact_url', sa.String(length=500), nullable=True),
    sa.Column('in_office', sa.Boolean(), nullable=False),
    sa.Column('next_election', sa.String(length=4), nullable=True),
    sa.Column('ocd_id', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('state_id', sa.String(length=2), nullable=False),
    sa.Column('missed_votes_pct', sa.Float(), nullable=True),
    sa.Column('votes_with_party_pct', sa.Float(), nullable=True),
    sa.Column('votes_against_party_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['states.abbreviation'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bioguide_id')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.String(length=20), nullable=False),
    sa.Column('bill_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('short_title', sa.Text(), nullable=False),
    sa.Column('sponsor_id', sa.String(length=10), nullable=False),
    sa.Column('govtrack_url', sa.String(length=500), nullable=True),
    sa.Column('introduced_date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_vote', sa.DateTime(), nullable=True),
    sa.Column('house_passage', sa.DateTime(), nullable=True),
    sa.Column('senate_passage', sa.DateTime(), nullable=True),
    sa.Column('enacted', sa.DateTime(), nullable=True),
    sa.Column('vetoed', sa.DateTime(), nullable=True),
    sa.Column('committees', sa.String(length=255), nullable=True),
    sa.Column('primary_subject', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('latest_major_action_date', sa.DateTime(), nullable=True),
    sa.Column('latest_major_action', sa.String(length=500), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sponsor_id'], ['representatives.bioguide_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id')
    )
    op.create_table('rep_follows',
    sa.Column('representative_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_constituent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['representative_id'], ['representatives.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('representative_id', 'user_id')
    )
    op.create_table('bill_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_follows',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'user_id')
    )
    op.create_table('bill_votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('is_downvote', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bill_id')
    )
    op.create_table('bill_comment_threads',
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('child', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child'], ['bill_comments.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['bill_comments.id'], ),
    sa.PrimaryKeyConstraint('parent', 'child')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bill_comment_threads')
    op.drop_table('bill_votes')
    op.drop_table('bill_follows')
    op.drop_table('bill_comments')
    op.drop_table('rep_follows')
    op.drop_table('bills')
    op.drop_table('representatives')
    op.drop_table('users')
    op.drop_table('states')
    # ### end Alembic commands ###
