"""create bills table, bill_comments table, bill_votes table, and self-referential bill_comment_threads table

Revision ID: 97dd0ba40714
Revises: 295672145ed7
Create Date: 2021-01-06 11:43:29.169567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97dd0ba40714'
down_revision = '295672145ed7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.String(length=20), nullable=False),
    sa.Column('bill_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('short_title', sa.Text(), nullable=False),
    sa.Column('sponsor_id', sa.String(length=10), nullable=False),
    sa.Column('govtrack_url', sa.String(length=500), nullable=True),
    sa.Column('introduced_date', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_vote', sa.DateTime(), nullable=True),
    sa.Column('house_passage', sa.Boolean(), nullable=True),
    sa.Column('senate_passage', sa.Boolean(), nullable=True),
    sa.Column('enacted', sa.Boolean(), nullable=True),
    sa.Column('vetoed', sa.Boolean(), nullable=True),
    sa.Column('committees', sa.String(length=255), nullable=True),
    sa.Column('primary_subject', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=False),
    sa.Column('latest_major_action_date', sa.DateTime(), nullable=True),
    sa.Column('latest_major_action', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['sponsor_id'], ['representatives.bioguide_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id')
    )
    op.create_table('bill_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill_votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('is_downvote', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'bill_id')
    )
    op.create_table('bill_comment_threads',
    sa.Column('parent', sa.Integer(), nullable=False),
    sa.Column('child', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child'], ['bill_comments.id'], ),
    sa.ForeignKeyConstraint(['parent'], ['bill_comments.id'], ),
    sa.PrimaryKeyConstraint('parent', 'child')
    )
    op.alter_column('representatives', 'ocd_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('representatives', 'ocd_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_table('bill_comment_threads')
    op.drop_table('bill_votes')
    op.drop_table('bill_comments')
    op.drop_table('bills')
    # ### end Alembic commands ###
