"""update bills table

Revision ID: 4ef7fbe5e42a
Revises: 97dd0ba40714
Create Date: 2021-01-07 09:54:50.115353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef7fbe5e42a'
down_revision = '97dd0ba40714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'house_passage')
    op.drop_column('bills', 'senate_passage')
    op.drop_column('bills', 'enacted')
    op.drop_column('bills', 'vetoed')
    op.add_column('bills', sa.Column('house_passage', sa.DateTime(), nullable=True))
    op.add_column('bills', sa.Column('senate_passage', sa.DateTime(), nullable=True))
    op.add_column('bills', sa.Column('enacted', sa.DateTime(), nullable=True))
    op.add_column('bills', sa.Column('vetoed', sa.DateTime(), nullable=True))
    op.add_column('bills', sa.Column('clicks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'clicks')
    # ### end Alembic commands ###
